[channel]
generator = utipod
xmlbase = None
title = "Gymnastics Method"
link = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
description = "This channel is about gymnastics joint preparation, strength and skill training. "

[channel "image"]
url = https://yt3.googleusercontent.com/ytc/AGIKgqN2UZvhu9x4O2P2SJyGfYeBhUc_k4Vapr95SvmhnA=s0

