[item]
guid = -JBqrdmeASs
title = "How to do L-sit (Step-by-step!)"
description = "Get the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start\n\nDo you want to learn advanced moves like the planche or front lever but you feel that it's impossible?\n \nThat's absolutely OK, because the truth is that you should not start with these exercises.\n \nSame as with other moves, no matter how much you like the Muscle up or the one arm chinup, until you don’t have the proper basics, they’ll seem impossible.\n \nIn static exercises it can be different but in reality, there is an order of exercises you should follow to ensure the maximal improvement.\n \nIn this video, I’m gonna show you the first static exercises you should start with, the L-sit!\n\nGet the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=-JBqrdmeASs
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 25 Jul 2021 00:00:00 -0000
enclosure = v/-JBqrdmeASs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/-JBqrdmeASs/maxresdefault.webp

