[item]
guid = -oxtjqnT5LI
title = "Mistake in Your Handstand Practice (Problem Fixed!)"
description = "We're sure you do or did this mistake while practicing handstand. Why am I so sure? I suggest you to look around how many people practice like that.\n\nIn this video @adamgodrosi is going to show you a very common mistake that people do while practicing the handstand. Most of them stop practicing because of it or getting injured. Let's see what this is, and what's the solution!\n\nCLICK HERE for a complete step-by-step Handstand tutorial, and more: https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=-oxtjqnT5LI
category = "Sports"
author = Gymnastics Method
pubdate = Fri, 29 Jan 2021 00:00:00 -0000
enclosure = v/-oxtjqnT5LI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/-oxtjqnT5LI/maxresdefault.jpg

