[item]
guid = 6Jn3ayipFiM
title = "5 Habits You Should Start Doing in 2023"
description = "New Year, New You! It's time to add some new habits to your lifestyle to live healthier, happier and more confident. Health could not be more valuable than these times! Not to mention, if you can successfully start doing these habits, you will definitely FEEL better, you can get in the best shape of your life, and spread good vibes! Who doesn't want that? Watch the video and get started today!\n\nIf you are interested in 5 more tips, get access to all the extended YouTube videos, all the Gymnastics Method workout programs, tutorials, series, daily workouts and nutrition tips:\n\nDOWNLOAD THE APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=6Jn3ayipFiM
category = "Sports"
author = Gymnastics Method
pubdate = Fri, 01 Jan 2021 00:00:00 -0000
enclosure = v/6Jn3ayipFiM.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/6Jn3ayipFiM/maxresdefault.webp

