[item]
description = "Get the shredded physique of a gymnast, JOIN HERE:  https://gymnasticsmethod.com/start\n\nYou can’t get into the right elbow lever position?\n\nMaybe your arms are too short for this?\n\nI don’t think so…\n\nIn this video, I’m going to show you a tip, which helped many of my students to get the perfect elbow lever!\n\nMany of my students had the issue, that they wanted to learn the elbow lever, but they couldn’t get into the right arm position while practicing.\n\nHowever, the elbow lever is all about the arm position.\n\nAnd if you’re not able to do it, after some time it may come to you mind: “is there something wrong with me? Are my arms too short or something like that?”\n\nIt’s true that everyone has a different body type, someone has longer arms, someone has shorter arms, but in most cases this is not the issue.\n\nLet's find out what's the problem and how you can fix it!\n\nGet the shredded physique of a gymnast, JOIN HERE:  https://gymnasticsmethod.com/start"
category = "Sports"
title = "Short Arms for Elbow lever? No... Try this! (Easy fix)"
pubdate = Sun, 30 Jan 2022 00:00:00 -0000
enclosure = v/7a2s4bGdXEU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/7a2s4bGdXEU/maxresdefault.webp

