[item]
description = "Get the shredded physique like gymnasts have, JOIN NOW: https://gymnasticsmethod.com/start\n\nEat the meals that I eat! Get 10% off now: https://chowmeals.link/4moV-VWE (Discount automatically validated at checkout)\n\nGet stronger in every calisthenics exercises with this simple shoulder blade/scapula workout at home! By the end of this video, you will understand why scapula exercises are so important before even doing a single push-up!\n\n(This is an old video which is embarrassing for me to watch back, sorry for the much promo as well, but the knowledge is legit so I keep it)\n\nFollow Us on Instagram: https://www.instagram.com/gymnastics.method/\nhttps://www.instagram.com/adamgodrosi/\n\nFacebook:\nhttps://www.instagram.com/gymnastics.method/\n\nTikTok:\nhttps://www.tiktok.com/@gymnasticsmethod/\n\n(Update: since then we have a new website and we don't have free trial anymore.)"
category = "Sports"
title = "SHOULDER BLADE WORKOUT AT HOME (Strength Secret)"
pubdate = Sun, 26 Jan 2020 00:00:00 -0000
enclosure = v/7J7YnUkOz_o.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/7J7YnUkOz_o/maxresdefault.webp

