[item]
description = "DOWNLOAD THE APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178\n\nMost people don’t warm up at all, or if they do so, it’s not enough or efficient. In this video, @adamgodrosi shows you an example for general warm-up, with gymnastic exercises and isolations, that can be done in just 5 minutes.\n\nYou can also learn why warm up is important, what type of warm ups we distinguish and a new approach how you should look at your warm-up routine and movements.\n\nIf you want to follow our joint preparation protocol, do our workout programs, tutorials listen to our nutrition guide podcasts and much more, join now on gymnasticsmethod.com!\n\nDOWNLOAD THE APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178"
category = "Sports"
title = "5-Minute Warm-Up Routine (Do It Before Every Workout!)"
pubdate = Sat, 23 Jan 2021 00:00:00 -0000
enclosure = v/9rFWkZViy-I.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/9rFWkZViy-I/maxresdefault.webp

