[item]
guid = _kMFS9a4CIs
title = "Gymnast Eating Schedule"
description = ""
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=_kMFS9a4CIs
category = "Sports"
author = Gymnastics Method
pubdate = Fri, 09 Jun 2023 00:00:00 -0000
enclosure = v/_kMFS9a4CIs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/_kMFS9a4CIs/maxresdefault.jpg

