[item]
description = "Doing pulling exercises at home without equipment is always tough question, but in this video @adamgodrosi collected 26 different variations which you can easily do using basic household items, like chairs, doors, broomsticks or towels. \n\nWe hope this video helps you to find the best pulling exercise you can do in your home!\n\nDOWNLOAD THE GYMNASTICS METHOD APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178"
category = "Sports"
title = "26 PULLING EXERCISES at HOME without Equipment"
pubdate = Sun, 12 Apr 2020 00:00:00 -0000
enclosure = v/ABUukFFa2RA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/ABUukFFa2RA/maxresdefault.webp

