[item]
description = "Improve your Perfect Pull-up with this 3 easy steps!\n\n1. Scapula pulls - Master step: 3 x 10\n2. Upper end-point hold + negatives - Master step: 3 x 5\n3. The goal: Perfect pull-up - 3-4 x 5-12 according to your goals\n\nTrain for the Pull-up 3 times a week! Add push, core and leg exercises for a full body workout!\n\nDOWNLOAD THE APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178"
category = "Sports"
title = "3 STEPS FOR THE PERFECT PULL-UP"
pubdate = Thu, 31 Jan 2019 00:00:00 -0000
enclosure = v/adBURUQ7Cko.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/adBURUQ7Cko/maxresdefault.webp

