[item]
description = "Start the new year and the new decade with a dope workout that helps you to build lean muscle and burn fat! Try this circuit workout at home or anywhere you want!\n\nFor more than 700 workout videos, become a member on https://gymnasticsmethod.com/start\n\nFREE warm-up and stretching routine: https://gymnasticsmethod.net/programs/prealityone\n\nFollow Us on Instagram @gymnastics.method and @adamgodrosi\nFacebook: @gymnasticsmethodcom\nTikTok @gymnasticsmethod   \nTwitch /gymnasticsmethod"
category = "Sports"
title = "2020 NEW YEAR NEW YOU WORKOUT (No equipment)"
pubdate = Fri, 03 Jan 2020 00:00:00 -0000
enclosure = v/adX9gJGGBEs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/adX9gJGGBEs/maxresdefault.webp

