[item]
guid = BgEQgmmddds
title = "Best Prehab Exercise for Pull-ups & Front lever"
description = "Get the shredded physique of a gymnast, JOIN HERE:  https://gymnasticsmethod.com/start\n\nThe best prehab exercise for pull-ups and front lever?!\n\nThe scapula pull is an advanced scapula stabilization exercise that many people don’t know or struggle with.\n\nSince this is an advanced exercise, it’s completely fine if you can’t do it right away.\n\nHowever the proper basics are required indeed! Watch the video to find out more!\n\nGet the shredded physique of a gymnast, JOIN HERE:  https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=BgEQgmmddds
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 24 Jul 2022 00:00:00 -0000
enclosure = v/BgEQgmmddds.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/BgEQgmmddds/maxresdefault.webp

