[item]
guid = BQtCn4bfL-4
title = "How to do Leg Raises (Best Sixpack Exercise?)"
description = "Get the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start\n\nIf I could only say one ab exercise that is the best for achieving the sixpack, which one would it be? \n\nI was thinking about it a lot, but eventually I always came to the conclusion, that the exercise I would say is the hanging leg raises. \n\nBut why? I’m gonna explain in this video!\n\nGet the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=BQtCn4bfL-4
category = "Sports"
author = Gymnastics Method
pubdate = Mon, 19 Jul 2021 00:00:00 -0000
enclosure = v/BQtCn4bfL-4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/BQtCn4bfL-4/maxresdefault.jpg

