[item]
guid = cJMzT3q8f8Q
title = "Best No Equipment Home Workout"
description = "How to train at home to get the best results? You need an all around full body workout with compound exercises! Watch this video to see a well-built and precisely planned full body workout! \n\nDo this workout for 4 weeks!\n\nBECOME A MEMBER ON GYMNASTICSMETHOD.COM AND GET ACCESS TO OUR !!NEW!!! 12-WEEK NO EQUIPMENT HOME WORKOUT PROGRAM!\nClick here: https://gymnasticsmethod.com\n\nFollow us on IG: https://www.instagram.com/gymnastics.method/\n\nTikTok: @gymnasticsmethod\n\nFacebook: https://www.facebook.com/GymnasticsMethodcom"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=cJMzT3q8f8Q
category = "Sports"
author = Gymnastics Method
pubdate = Mon, 23 Mar 2020 00:00:00 -0000
enclosure = v/cJMzT3q8f8Q.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/cJMzT3q8f8Q/sddefault.jpg

