[item]
guid = CzwMAFLH2p0
title = "You CAN Do Chest to Bar Pull-ups! (Guaranteed!)"
description = "DOWNLOAD THE APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178\n\nYou simply can’t touch the bar with your chest while doing pull-ups? There are only a few inches missing but it feels impossible?\n\nSometimes you’re even thinking there is something wrong with your body?\n\nThis is probably not the case…\n\nIn this video, I’m going to prove you with a simple test that you’re actually able to do chest to bar pull-ups, I’ll also tell you what are the missing links and how to overcome this problem.\n\n--------------------------------------------------------------\n\nDOWNLOAD THE APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=CzwMAFLH2p0
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 19 Jun 2022 00:00:00 -0000
enclosure = v/CzwMAFLH2p0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/CzwMAFLH2p0/maxresdefault.webp

