[item]
guid = D3ZWTQww7Yk
title = "Learn this before Handstand! (Shoulder stand step-by-step!)"
description = "Get the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start\n\nHandstand is a really popular exercise, many people practice it, it’s there in many types of training, but not many learn the proper handstand.\n\nWhat if I say you can make the path to handstand easier with a much simpler exercise that almost everyone misses?\n\nBefore you start practicing the handstand, there is another skill I suggest you to learn if you want to make your handstand and handstand pushups journey easier! And this is the shoulder stand.\n\nIn this video, I’m gonna show you this beginner skill, which we can say is a milestone on the way to the handstand.\n\nGet the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=D3ZWTQww7Yk
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 01 Aug 2021 00:00:00 -0000
enclosure = v/D3ZWTQww7Yk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/D3ZWTQww7Yk/maxresdefault.webp

