[item]
guid = dLSJu7wKSOs
title = "#1 Push-up Mistake Everyone Makes (+ How to Fix it)"
description = "Get the shredded physique of a gymnast, JOIN HERE: https://gymnasticsmethod.com/start\n\nThere is a typical push-up mistake that almost everyone makes.\n\nThis is not a top 5-10 mistake that you can do in a push-up video with finding every possible mistake can be done in a single push-up.\n\nI made this video to help you fixing a particular mistake that I saw many people making from beginner to the more experienced. \n\nThe interesting thing about this mistake that the person making it is striving for the tip top perfect execution.\n\nAfter getting into the starting position, makes sure that everything is perfect, everything is in line, but right after starting the exercise the mistake shows up.\n\nThe elbows move backward, away from above the wrist.\n\nIs this a problem?\n\nOf course we can say, it depends.\n\nIt’s not a problem if you have the right preparations and you want to do the exercise more triceps centric.\n\nBut if you want to do the regular execution striving for the best and you haven’t prepare you joints it’s certainly a problem, since most of the people who do the push up like this complain about elbow pain.\n\nNot to mention that for many, this small mistake starts a whole domino effect. Let's see how to fix it!\n\nGet the shredded physique of a gymnast, JOIN HERE: https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=dLSJu7wKSOs
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 06 Nov 2022 00:00:00 -0000
enclosure = v/dLSJu7wKSOs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/dLSJu7wKSOs/maxresdefault.webp

