[item]
guid = EjGMdET7DTQ
title = "BEST PULL-UP BAR WORKOUT (All levels)"
description = "Become member now and get access to all our tutorials such as Muscle Up, Dips, Pull-ups, Leg raises and Pistol squats to master this workout on the advanced level!\n\nClick here and get started now: https://gymnasticsmethod.net/start\n\nCheck out the Best Pull-up Bar Workout including all training levels! This workout is going to help you to build muscle and burn fat at the same time!\n\nClick here and become a member to get access to more than 600 tutorial videos for discounted price: https://gymnasticsmethod.net/start\n\nFollow us on Instagram: @gymnastics.method\n@adamgodrosi"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=EjGMdET7DTQ
category = "Sports"
author = Gymnastics Method
pubdate = Fri, 11 Oct 2019 00:00:00 -0000
enclosure = v/EjGMdET7DTQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/EjGMdET7DTQ/sddefault.webp?v=5dbd0ebe

