[item]
description = "SEE MORE PROGRAMS, TUTORIALS ON https://gymnasticsmethod.net/ WITH 7-DAY FREE TRIAL!\n\n4-WEEK SIXPACK PROGRAM for all training levels:\n\n1st WEEK: \nHollow body position - Everyday 4-6 x 15-30 sec\n\n2nd WEEK:\nTuck crunches - Everyday 4-6 x 10-30 reps\n\n3rd WEEK:\nSupported knee raises - 5 times a week 3-5 x 10-20 reps\n\n4th WEEK:\nSupported leg raises - 4 times a week 3-5 x 5-12 reps\n\nGood luck, guys!\n\nClick here for more: https://gymnasticsmethod.net/\n\nFollow us on Instagram: https://www.instagram.com/gymnastics.method/"
category = "Sports"
title = "SHREDDED SIXPACK | 4 WEEKS | ANYWHERE"
pubdate = Sun, 24 Feb 2019 00:00:00 -0000
enclosure = v/Em1lDeOqzes.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/Em1lDeOqzes/maxresdefault.webp

