[item]
guid = F7i5nqkjJ1I
title = "Lower Body Mobility with ONE exercise!"
description = "Join now, and start to train like a gymnast on https://gymnasticsmethod.com/start\n\nWhat if I tell you that with only one exercise, you can fix all your lower body mobility problems?\n\nI mean the tight ankles, painful knees, anterior pelvic tilt which has effect to your posture and your lower back hurts because of it.\n\nYes, you can fix all these with just only one exercise! Watch the video to learn more!\n\nJoin now, and start to train like a gymnast on https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=F7i5nqkjJ1I
category = "Sports"
author = Gymnastics Method
pubdate = Fri, 14 May 2021 00:00:00 -0000
enclosure = v/F7i5nqkjJ1I.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/F7i5nqkjJ1I/maxresdefault.webp

