[item]
description = "DOWNLOAD THE APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178\n\nWhy is the press to handstand so difficult?\n\nIn this video, Gabo Saturno and I will tell you about the 4 areas that most people are missing for the perfect press to handstand!\n\nGo and subscribe to @SaturnoMovement for the next collab video!\n\nDOWNLOAD THE APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178"
category = "Sports"
title = "4 Secrets of Press To Handstand with Gabo Saturno"
pubdate = Sun, 23 Oct 2022 00:00:00 -0000
enclosure = v/fn-GS5do_Dc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/fn-GS5do_Dc/maxresdefault.webp

