[item]
guid = hWDqOcORZak
title = "How to Increase Wrist Mobility (Fix Wrist & Elbow Pain)"
description = "People always ask me what can they do with wrist pain or increase wrist mobility.\n\nA lot of people have issues with the wrist joint. Many of them are trying “treat the symptoms” by using wrist wraps or parallettes, because wrist wraps help to decrease the load of the wrist joint and parallettes put your hands in a position where you don’t need that much mobility as if you’re doing the same on the floor.\n\nThere are some people who think that supporting on the floor is particularly unhealthy and harmful…..\n\nBut is this really true? What should you do to increase wrist mobility without compromises, train with pain, or use wrist warps at all costs.\n\n@adamgodrosi will tell you in this video!\n\nJoin now, and start to train like a gymnast on https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=hWDqOcORZak
category = "Sports"
author = Gymnastics Method
pubdate = Fri, 26 Mar 2021 00:00:00 -0000
enclosure = v/hWDqOcORZak.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/hWDqOcORZak/sddefault.jpg

