[item]
description = "Become a member and get full access to all of our programs, tutorials and 600+ videos!\nSTART YOUR FREE 7-DAY TRIAL NOW: https://gymnasticsmethod.net/subscription/subscribe/"
category = "Sports"
title = "GYMNASTICS METHOD - START YOUR OWN JOURNEY TODAY!"
pubdate = Mon, 03 Dec 2018 00:00:00 -0000
enclosure = v/iRFaG9ce1ZI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/iRFaG9ce1ZI/maxresdefault.webp

