[item]
description = "Get the shredded physique of a gymnast, JOIN HERE: https://gymnasticsmethod.com/start\n\n5 best cues for the perfect pull-up\n\nIf you want to unlock your first pull-up or just perfect your form, there are several cues to help to reach your goal!\n\nAnd I don’t talk about preparation exercises or progressions, but the power of your mind.\n\nIn my experience imaging different cues, changing the perspective of a movement helps many people to execute the exercises better.\n\nFor example, instead of imaging pushing up yourself in a push up, imagine to push the ground away from you.\n\nWith similar cues you can trick your brain, think outside that box and flip the perspective, so you can make challenging tasks feel easier.\n\nIn this video, I’m going to show you 5 cues that helped many of my students to do perfect pull-ups!\n\nGet the shredded physique of a gymnast, JOIN HERE: https://gymnasticsmethod.com/start"
category = "Sports"
title = "5 BEST PULL-UP CUES (Results Guaranteed!)"
pubdate = Sun, 11 Dec 2022 00:00:00 -0000
enclosure = v/j4nSQlvQ6nI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/j4nSQlvQ6nI/maxresdefault.webp

