[item]
description = "Let’s say you can’t go anywhere to workout... The weather is not ideal, there is no calisthenics park nearby, the gym is closed or too far, and you don’t have any equipment at home. What can you do? What if I say, you can do an effective full body workout using a single chair? But how? Let’s find out!\n\nFollow along this workout with Adam, and do the other two sessions + get access to all the Gymnastics Method programs, tutorials, nutrition guide and much more! \nCLICK HERE TO START: https://gymnasticsmethod.com/start"
category = "Sports"
title = "Full Body Workout Using a CHAIR"
pubdate = Fri, 15 Jan 2021 00:00:00 -0000
enclosure = v/jQr1ZjXTdmg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/jQr1ZjXTdmg/maxresdefault.webp

