[item]
guid = ku5vexaQMtw
title = "How to Fix Your Posture (The True Solution!)"
description = "Get the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start\n\nDo you want to fix your bad posture?\n\nThen this video is for you, but this is gonna be a bit different, than the usual videos.\n\nToday, I’m not gonna show you the best exercise or the top 5 exercises to fix your posture, but will teach you the principles of how this should be done the best way.\n\nWhat’s the cause of bad posture, why you won’t be able to get rid of it for the rest of your life, unless if you do something, and what should you do to say goodbye to it and what principles should you follow.\n\nBy the end of this video, you’ll understand what should you do in order to fix your posture, and you’ll be able to implement the principles to even build your routine that’s the best for you!\n\nGet the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=ku5vexaQMtw
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 28 Nov 2021 00:00:00 -0000
enclosure = v/ku5vexaQMtw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ku5vexaQMtw/maxresdefault.jpg

