[item]
guid = KZPMdWy3mZA
title = "3 WAYS to Do CHEST TO BAR PULL-UP"
description = "Get the shredded physique of a gymnast, JOIN HERE: https://gymnasticsmethod.com/start\n\nYou can do chest to bar pull-ups 3 ways!\n\nBut unfortunately that doesn’t mean that all 3 are good.\n\nIn this video I’m going to tell you what you need for the perfect execution!\n\nGet the shredded physique of a gymnast, JOIN HERE: https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=KZPMdWy3mZA
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 20 Nov 2022 00:00:00 -0000
enclosure = v/KZPMdWy3mZA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/KZPMdWy3mZA/maxresdefault.webp

