[item]
guid = lQZD-fauVmU
title = "How to do Straight Bar Dips? (What You Need To Know)"
description = "Get the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start\n\nWe usually do dips on dip bars, parallel bars or two chairs. However, you can do it on a single bar as well, you can give your body a different stimulus and it’s especially useful, if you wanna learn the bar muscle up.\n\nDoing straight bar dips is a little bit different than on the parallel bars. In this video, I’ll tell you what you need to know!\n\nGet the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=lQZD-fauVmU
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 10 Oct 2021 00:00:00 -0000
enclosure = v/lQZD-fauVmU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/lQZD-fauVmU/maxresdefault.jpg

