[item]
description = "You might think your shape is over... the holidays are here! Christmas meals and New Years Eve will ruin your body... Are you sure? Follow these tips and stay in shape while enjoying your favorite meals, be rested and start the New Year recharged and motivated!\n\nCLICK HERE, sign up and get access to all of our extended youtube videos, all workout programs, tutorials, nutrition, daily workouts and much more, click the link below and join the Gymnastics Method community right now!\nhttps://gymnasticsmethod.com/start"
category = "Sports"
title = "5 Tips To AVOID GAINING FAT During The Holidays (Works Anytime)"
pubdate = Wed, 23 Dec 2020 00:00:00 -0000
enclosure = v/mlamt4EIKH0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/mlamt4EIKH0/maxresdefault.webp

