[item]
guid = nEzX4EsNsc0
title = "YT bumper videó"
description = "Challange yourself!"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=nEzX4EsNsc0
category = "Sports"
author = Gymnastics Method
pubdate = Fri, 01 Mar 2019 00:00:00 -0000
enclosure = v/nEzX4EsNsc0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/nEzX4EsNsc0/maxresdefault.webp

