[item]
description = "Challange yourself!"
category = "Sports"
title = "YT bumper videó"
pubdate = Fri, 01 Mar 2019 00:00:00 -0000
enclosure = v/nEzX4EsNsc0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/nEzX4EsNsc0/maxresdefault.webp

