[item]
description = "Check out @adamgodrosi's quick 3 minute wrist mobility routine, and increase your mobility, prevent injuries and relief the tension in your forearms!\n\nBecome a member now for 700+ tutorial videos: https://gymnasticsmethod.com/start\n\nFollow us on Instagram: @gymnastics.method @adamgodrosi\n\nFacebook: @gymnasticsmethodcom\n\nTiktok: @gymnasticsmethod"
category = "Sports"
title = "3 Minute Wrist Mobility Routine / Fix wrist and elbow pain!"
pubdate = Fri, 13 Dec 2019 00:00:00 -0000
enclosure = v/oBvxBeiPVcI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/oBvxBeiPVcI/maxresdefault.webp

