[item]
description = "Check out our Planche workout with @johnoslager using one of the best methods to gain strength in static exercises and their dynamic implementations. Hope you guys enjoy it! Give a thumbs up and subscribe to the channel and John's channel!\n\nFollow @johnoslager on Instagram: https://www.instagram.com/johnoslager/\n\nBECOME A MEMBER ON GYMNASTICSMETHOD.COM AND GET ACCESS TO OUR !!NEW!!! 12-WEEK NO EQUIPMENT HOME WORKOUT PROGRAM!\nClick here: https://gymnasticsmethod.com\n\nFull body No equipment workouts here on YouTube:: \nhttps://www.youtube.com/watch?v=cJMzT3q8f8Q&t=22s\nhttps://www.youtube.com/watch?v=-P6eVUk16aA\n\nWebsite: https://gymnasticsmethod.com/\nTikTok: https://www.tiktok.com/@gymnasticsmethod\nFacebook: https://www.facebook.com/GymnasticsMethodcom\nInstagram: https://www.instagram.com/gymnastics.method/\nTwitch: https://www.twitch.tv/gymnasticsmethod"
category = "Sports"
title = "BEST METHOD TO GAIN STRENGTH with John Oslager (Planche workout)"
pubdate = Mon, 25 May 2020 00:00:00 -0000
enclosure = v/og4Tk9Uqwz8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/og4Tk9Uqwz8/maxresdefault.webp

