[item]
guid = OkRqg9unLws
title = "GET RIPPED - Full Body Home Workout | No equipment needed"
description = "Use this Full Body Home Workout to GET RIPPED!\n\n1. Forward lean push-ups\n2. Inverted rows\n3. Supported knee raises\n4. Half pistol squats\n\nDo 3-5 sets and 10-15 reps!\n\nDo this workout 2-3 times a week for 4-6 weeks for the maximal results!\n\nJOIN THE COMMUNITY! DOWNLOAD THE APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=OkRqg9unLws
category = "Sports"
author = Gymnastics Method
pubdate = Tue, 12 Feb 2019 00:00:00 -0000
enclosure = v/OkRqg9unLws.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/OkRqg9unLws/maxresdefault.webp

