[item]
guid = opobIGGKp0g
title = "Most Important BACK EXERCISE? (You're missing out!)"
description = "Get the shredded physique of a gymnast, JOIN HERE:  https://gymnasticsmethod.com/start\n\nThe Ring face pull is an unknown exercise for many, it’s also neglected, however it’s extremely useful.\n\nIt’s improving your posture while building noticable muscle mass, not to mention shoulder health.\n\nThe Face pull targets muscles that most people barely use: the trapezius, the rombiods, the rear delts and the rotator cuff muscles.\n\nUnfortunately the sedentary lifestyle is the cause of the weakening and stretching of these muscles while breaking the harmony of your structural balance.\n\nBut the face pull can balance this out!\n\nLet’s find out how!\n\nGet the shredded physique of a gymnast, JOIN HERE:  https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=opobIGGKp0g
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 02 Oct 2022 00:00:00 -0000
enclosure = v/opobIGGKp0g.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/opobIGGKp0g/maxresdefault.jpg

