[item]
guid = PFWt4dskXco
title = "Grow Your BICEPS and SHOULDERS with this Straight-arm Exercise"
description = ""
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=PFWt4dskXco
category = "Sports"
author = Gymnastics Method
pubdate = Sat, 17 Jun 2023 00:00:00 -0000
enclosure = v/PFWt4dskXco.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/PFWt4dskXco/maxresdefault.jpg

