[item]
guid = podUEnHEedU
title = "3 FAVORITE STATIC PLANCHE PROGRESSIONS"
description = "Wanna grab Planche? Check out @adamgodrosi's 3 favorite static planche progressions, and get those planche gains!\n\nFREE PREHAB PROGRAM: https://gymnasticsmethod.net/programs/prealityone\n\nSTART DISCOUNTED MEMBERSHIP AND GET FULL ACCESS:\nhttps://gymnasticsmethod.net/start\n\nMORE THAN 20 TUTORIALS:\nhttps://gymnasticsmethod.net/tutorials\n\nFollow us on Instagram:\nhttps://www.instagram.com/gymnastics....\n\nFacebook:\nhttps://www.facebook.com/GymnasticsMe...\n\nTikTok:\n@gymnasticsmethod\n\nLIVE TWITCH WORKOUTS COMING SOON!\nhttps://www.twitch.tv/gymnasticsmethod"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=podUEnHEedU
category = "Sports"
author = Gymnastics Method
pubdate = Fri, 22 Nov 2019 00:00:00 -0000
enclosure = v/podUEnHEedU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/podUEnHEedU/maxresdefault.webp

