[item]
guid = r1x6rmMtrVc
title = "Gymnast Back Exercise You NEVER DO!"
description = "DOWNLOAD THE APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178\n\nThere is a typical gymnast back exercise that you probably never do, however you could build muscle, strength and mobility at the same time.\n\nIn this video, I’ll show you all you need to know!\n\nThis exercise is the scapula swing. If you’ve been watching the channel for a while, you’ve heard about this exercise in the ”Top 12 typical gymnast exercises you’ve never do” video and as I promised, now I’m going to tell you more about this exercise.\n\nThe scapula swing is a typical gymnast exercise that many don’t even know, however it has many benefits.\n\nLet’s see what are these and how you should build it up the safest way!\n\nAthletes shown in the video: Ivan Ivankov, Jordan Jovtchev, Sam Mikulak\n\nDOWNLOAD THE APP:\n\nGoogle Play Store: https://play.google.com/store/apps/details?id=com.virfortis.gymmethod\n\nApp Store: https://apps.apple.com/us/app/gymnastics-method/id1661126178"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=r1x6rmMtrVc
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 17 Apr 2022 00:00:00 -0000
enclosure = v/r1x6rmMtrVc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/r1x6rmMtrVc/maxresdefault.webp

