[item]
description = "Get the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start\n\nI bet you don’t do you dips as I ask you now…\n\nIn this video I challenge you to do dips with me the way and pace I will do.\n\nBut what is this secret kind of dips that I challenge you for, and say, many people never do?\n\nStay with me and let's see! This is not the 100 dip challenge, but something much more useful, and life changing. Once you start doing dips like this, you'll see better results!\n\nGet the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start"
category = "Sports"
title = "NOT the 100 DIP CHALLENGE (This is Life Changing!)"
pubdate = Sun, 05 Sep 2021 00:00:00 -0000
enclosure = v/TO3uleW_GDk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/TO3uleW_GDk/maxresdefault.webp

