[item]
guid = u0sdWsKSNt4
title = "How to Fix Lower Back Pain (Secret Gymnast Stretch)"
description = "!!! HANDSTAND SHIRT IS AVAILABLE !!!\nhttps://webshop.gymnasticsmethod.com/\n\nGet the shredded physique of a gymnast, JOIN HERE:  https://gymnasticsmethod.com/start\n\nGet shredded the most convenient way: delicious meals, prepared for you! Easy to track calories and macros, meals are ready in under 2 minutes! This is what I eat, give it a try! \n10% discount will be applied at the checkout automatically: https://chowmeals.link/4moV-VWE\n\nIf you have tight lower back from sitting, you can’t fold forward because you have tight Hamstrings, there is a typical gymnast stretch that can help you in all these.\n\nThis exercise is the Jefferson Curl, and in this video I’m going to tell you everything you need to know about it.\n\nWe’ll check the keypoints of the right exercution in a bit, but before that it’s really important for you to understand the following.\n\nFor the first look, Jefferson curl looks scary, especially if you see someone doing it with weight.\n\nSeeing the round back and the weight reminds most of the people of an instant hernia, and that this exercise is not healthy at all.\n\nHowever, it’s not exactly like that.\n\nWatch the video to find out, how the Jefferson Curl could change your life!\n\nGet the shredded physique of a gymnast, JOIN HERE:  https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=u0sdWsKSNt4
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 12 Jun 2022 00:00:00 -0000
enclosure = v/u0sdWsKSNt4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/u0sdWsKSNt4/maxresdefault.webp

