[item]
description = "Try this beginner sixpack workout in only 12 minutes!\n\nGet full access for all of our contents now, for a limited time, discounted price: http://gymnasticsmethod.com/start\n\nFollow us on Instagram: https://www.instagram.com/gymnastics.method/\n\nFacebook: https://www.facebook.com/GymnasticsMethodcom\n\nTiktok: @gymnasticsmethod"
category = "Sports"
title = "12 mins Black Friday Abs workout for Beginners"
pubdate = Fri, 29 Nov 2019 00:00:00 -0000
enclosure = v/UJOnt3zUsL4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/UJOnt3zUsL4/maxresdefault.webp

