[item]
guid = UJOnt3zUsL4
title = "12 mins Black Friday Abs workout for Beginners"
description = "Try this beginner sixpack workout in only 12 minutes!\n\nGet full access for all of our contents now, for a limited time, discounted price: http://gymnasticsmethod.com/start\n\nFollow us on Instagram: https://www.instagram.com/gymnastics.method/\n\nFacebook: https://www.facebook.com/GymnasticsMethodcom\n\nTiktok: @gymnasticsmethod"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=UJOnt3zUsL4
category = "Sports"
author = Gymnastics Method
pubdate = Fri, 29 Nov 2019 00:00:00 -0000
enclosure = v/UJOnt3zUsL4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/UJOnt3zUsL4/sddefault.jpg?v=5de155bd

