[item]
guid = v0-VcraPSDw
title = "No Calisthenics Park? No Problem! (Upper body workout)"
description = "My first outdoor workout after 2 months home quarantine. No Calisthenics park open, but it didn't stop me! Check out this upper body workout, and build muscle with these great bodyweight and shoulder exercises!\n\nBECOME A MEMBER ON GYMNASTICSMETHOD.COM AND GET ACCESS TO OUR !!NEW!!! 12-WEEK NO EQUIPMENT HOME WORKOUT PROGRAM!\nClick here: https://gymnasticsmethod.com\n\nFull body No equipment workouts: \nhttps://www.youtube.com/watch?v=cJMzT3q8f8Q&t=22s\nhttps://www.youtube.com/watch?v=-P6eVUk16aA\n\nWebsite: https://gymnasticsmethod.com/\nTikTok: https://www.tiktok.com/@gymnasticsmethod\nFacebook: https://www.facebook.com/GymnasticsMethodcom\nInstagram: https://www.instagram.com/gymnastics.method/\nTwitch: https://www.twitch.tv/gymnasticsmethod"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=v0-VcraPSDw
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 10 May 2020 00:00:00 -0000
enclosure = v/v0-VcraPSDw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/v0-VcraPSDw/maxresdefault.webp

