[item]
guid = V3Xl4uAIfSY
title = "How to BUILD Your SHOULDERS at Home with Elastic Band"
description = "Check out @adamgodrosi's top 3 favorite elastic band shoulder exercises that you can easily do at home!\n\nIf you want to see the PREHAB exercises as well, become our Patron and watch the full length video on our Patreon page!\nClick here to watch and support: https://www.patreon.com/gymnasticsmethod\n\nBECOME A MEMBER ON GYMNASTICSMETHOD.COM AND GET ACCESS TO OUR !!NEW!!! 12-WEEK NO EQUIPMENT HOME WORKOUT PROGRAM!\nClick here: https://gymnasticsmethod.com\n\nSTART YOUR 7-DAY FREE TRIAL AND START THE PROGRAM TODAY!\n\n Full body No equipment workout videos:\nhttps://www.youtube.com/watch?v=cJMzT3q8f8Q&t=22s\nhttps://www.youtube.com/watch?v=-P6eVUk16aA\n\nFollow us on IG: https://www.instagram.com/gymnastics.method/\n\nAdam's Instagram: https://www.instagram.com/adamgodrosi/\n\nTikTok: @gymnasticsmethod\n\nFacebook: https://www.facebook.com/GymnasticsMethodcom"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=V3Xl4uAIfSY
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 05 Apr 2020 00:00:00 -0000
enclosure = v/V3Xl4uAIfSY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/V3Xl4uAIfSY/maxresdefault.webp

