[item]
description = "Get the shredded physique of a gymnast, JOIN HERE: https://gymnasticsmethod.com/start\n\nIf you want to do the most honest push-up test in your life, just listen to this video, DON'T COUNT THE REPS and DON'T LOOK AT THE SCREEN when the test starts.\n\nJust listen to my voice and the instructions,  and if you can't perform the push-up with perfect form anymore, ONLY AFTER  THAT LOOK AT THE SCREEN to see how many reps you could do.\n\nAre you ready? Let's get it!\n\nGet the shredded physique of a gymnast, JOIN HERE: https://gymnasticsmethod.com/start"
category = "Sports"
title = "Push-up PACER TEST (How many reps can you do?)"
pubdate = Sun, 04 Dec 2022 00:00:00 -0000
enclosure = v/VJXSZqGrRR0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/VJXSZqGrRR0/maxresdefault.webp

