[item]
guid = WSY-xPU_hyU
title = "The Most Underrated Core Exercise? (Do This For Strength & 6pack)"
description = "There is a core exercise that you may not have even heard of, but if you have, you don’t do it regularly, or you don’t do it at all.. Big mistake!\n\nWatch the video and find out, which one is this exercise and why is it very useful!\n\nGet access to all the Gymnastics Method workout programs, tutorials like planche, handstand or muscle up, nutrition guide, daily workouts and much more, click the link below and become a member now on https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=WSY-xPU_hyU
category = "Sports"
author = Gymnastics Method
pubdate = Fri, 19 Feb 2021 00:00:00 -0000
enclosure = v/WSY-xPU_hyU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/WSY-xPU_hyU/maxresdefault.webp

