[item]
guid = WV98lz7JdWg
title = "10 Pull-ups = Muscle up?! (True or False?)"
description = "Get the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start\n\nIt’s a pretty common statement that if you can do 10 pull ups, you should to be able to do the muscle up.\n\nBut is this really true? In most cases, unfortunately it’s not. I’ll tell why you in this video!\n\nGet the shredded physique of a gymnast! Join now on https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=WV98lz7JdWg
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 26 Sep 2021 00:00:00 -0000
enclosure = v/WV98lz7JdWg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/WV98lz7JdWg/maxresdefault.webp

