[item]
guid = XD5E3tuLIY4
title = "Strong & Mobile Ankles by Gymnasts"
description = "Join now, and start to train like a gymnast on https://gymnasticsmethod.com/start\n\nWhile we are standing or simply changing our location by walking or running, the first main joints that connect us to the ground are located in our feet and ankles.\n\nWe can hear a lot about ankle mobility, since many people have problem with that, but what about stability and strength?\n\nIn this video I’m gonna show you some exercises that you can mobilize and stabilize your ankle range of motion from the gymnastics perspective.\n\nYou’ll be able to benefit from these exercises in your everyday life or in any sport you do!\n\nJoin now, and start to train like a gymnast on https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=XD5E3tuLIY4
category = "Sports"
author = Gymnastics Method
pubdate = Fri, 21 May 2021 00:00:00 -0000
enclosure = v/XD5E3tuLIY4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/XD5E3tuLIY4/maxresdefault.jpg

