[item]
description = "Join now, and start to train like a gymnast on https://gymnasticsmethod.com/start\n\nWhile we are standing or simply changing our location by walking or running, the first main joints that connect us to the ground are located in our feet and ankles.\n\nWe can hear a lot about ankle mobility, since many people have problem with that, but what about stability and strength?\n\nIn this video I’m gonna show you some exercises that you can mobilize and stabilize your ankle range of motion from the gymnastics perspective.\n\nYou’ll be able to benefit from these exercises in your everyday life or in any sport you do!\n\nJoin now, and start to train like a gymnast on https://gymnasticsmethod.com/start"
category = "Sports"
title = "Strong & Mobile Ankles by Gymnasts"
pubdate = Fri, 21 May 2021 00:00:00 -0000
enclosure = v/XD5E3tuLIY4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/XD5E3tuLIY4/maxresdefault.webp

