[item]
guid = YTBChReTM_0
title = "Top 2 Most Forgotten Exercises For The Perfect Muscle Up"
description = "What are the Top 2 Most Forgotten Exercises For The Perfect Muscle Up? Let's find out!\n\nDid you think these exercises would help you? They will, 100%!\n\nCLICK HERE to watch the full video with the 2 step-by-step guide to master these exercises!\nhttps://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=YTBChReTM_0
category = "Sports"
author = Gymnastics Method
pubdate = Thu, 17 Dec 2020 00:00:00 -0000
enclosure = v/YTBChReTM_0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/YTBChReTM_0/hqdefault.webp

