[item]
guid = zUhLXRaVgxo
title = "Insane Gymnast Sixpack Workout You Can Do Anywhere (Follow along!)"
description = "Get the shredded physique of a gymnast, JOIN HERE:  https://gymnasticsmethod.com/start\n\nInsane Gymnast Sixpack Workout (Follow along!)\n\nIf you want to have gymnast sixpack and core strength, then this video is for you!\n\nIn this video, we’re gonna do the next level of the gymnast sixpack workout series, where we your the compression to another level!\n\nBefore we start, you need to that this video is the part of a video series. In the first half of the gymnast core workout series we focused on the extended body position strength, and did beginner, intermediate and advanced workout, and now we do the same with the compression strength.\n\nWhat you need to know about this series that I upload the videos in every 4 weeks, which is only important in the beginning - if you watch this later on, you’ll find all videos in a dedicated playlist.\n\nThis video is the intermediate level of the compression strength workouts.\n\nLearn more about the exercises and follow along the workout!\n\nThumbnail: Brandon Wynn\n\nGet the shredded physique of a gymnast, JOIN HERE:  https://gymnasticsmethod.com/start"
source = https://www.youtube.com/channel/UCaswSQszj4JrK2d58h5y_Bw
link = https://www.youtube.com/watch?v=zUhLXRaVgxo
category = "Sports"
author = Gymnastics Method
pubdate = Sun, 01 May 2022 00:00:00 -0000
enclosure = v/zUhLXRaVgxo.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/zUhLXRaVgxo/maxresdefault.webp

